name: Feature Request
description: Suggest an idea or new feature for Wishy Clip
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: pitch
    attributes:
      label: Feature Pitch
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: How should this feature work?
    validations:
      required: true
